// Render chart rebuttal cards to 1600x900 PNGs for Twitter native-image posting.
//
//   pnpm render:charts
//
// Separate from render.mjs (the 1200x630 link-unfurl OG cards): these are meant
// to be UPLOADED as native images into a tweet/reply, not served as og:image.
// So: 16:9, no /s/ stub, no content hash — stable filenames the author can grab
// and re-upload. Source of each card is og-cards/chart-<slug>.html.
//
// Output: web/public/og/charts/<slug>.png   (also copied into dist/ by Vite)

import { chromium } from 'playwright'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, basename } from 'node:path'
import { mkdirSync, writeFileSync, readdirSync } from 'node:fs'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(here, '../public/og/charts')
mkdirSync(outDir, { recursive: true })

const cards = readdirSync(here)
  .filter((f) => f.startsWith('chart-') && f.endsWith('.html'))
  .map((f) => ({ file: f, slug: basename(f, '.html').replace(/^chart-/, '') }))

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2 })

const warnings = []
page.on('pageerror', (e) => warnings.push(`  script error: ${e.message}`))

for (const card of cards) {
  warnings.length = 0
  await page.goto('file://' + resolve(here, card.file))
  await page.waitForLoadState('networkidle')

  // Guard: chart content that overflows its own viewBox renders clipped, and
  // slack inside the viewBox shows up as dead space above the footer. Both have
  // shipped silently before, so fail loudly instead.
  const geom = await page.evaluate(() => {
    const box = document.querySelector('.cc-chart')
    const svg = box && box.querySelector('svg')
    if (!svg) return null
    const vb = svg.viewBox.baseVal
    const bb = svg.getBBox()
    const r = box.getBoundingClientRect()
    return {
      overflowX: Math.round(bb.x + bb.width - (vb.x + vb.width)),
      overflowY: Math.round(bb.y + bb.height - (vb.y + vb.height)),
      slackY: Math.round(vb.y + vb.height - (bb.y + bb.height)),
      letterboxY: Math.round(r.height - (r.width * vb.height) / vb.width),
    }
  })
  if (geom) {
    if (geom.overflowY > 2) warnings.push(`  CLIPPED: content runs ${geom.overflowY}u past the bottom of the viewBox`)
    if (geom.overflowX > 2) warnings.push(`  CLIPPED: content runs ${geom.overflowX}u past the right of the viewBox`)
    const dead = Math.max(0, geom.letterboxY) + Math.max(0, geom.slackY)
    if (dead > 90) warnings.push(`  DEAD SPACE: ~${dead}px unused below the chart (letterbox ${geom.letterboxY}, viewBox slack ${geom.slackY})`)
  }

  const buf = await page.screenshot({ clip: { x: 0, y: 0, width: 1600, height: 900 } })
  const out = resolve(outDir, `${card.slug}.png`)
  writeFileSync(out, buf)
  console.log('rendered og/charts/' + card.slug + '.png')
  for (const w of warnings) console.log(w)
}

await browser.close()

// Contact sheet, regenerated every run so it can never drift from the card set.
const rows = cards.map((c) =>
  `  <figure><img src="../public/og/charts/${c.slug}.png" alt="${c.slug}" loading="lazy">` +
  `<figcaption>${c.slug}</figcaption></figure>`).join('\n')
writeFileSync(resolve(here, 'gallery.html'), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Chart cards \u2014 contact sheet</title>
<style>
  body { margin:0; padding:36px 40px 80px; background:#e9e9e4; color:#1b1b1d;
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif; }
  h1 { font-size:26px; margin:0 0 4px; }
  .sub { color:#6b6b70; font-size:14px; margin:0 0 28px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(620px,1fr)); gap:32px; }
  figure { margin:0; background:#fff; border:1px solid #cfcdc7; border-radius:10px; padding:12px; }
  figure img { width:100%; height:auto; display:block; border:1px solid #eee; border-radius:4px; }
  figcaption { font-size:13px; color:#6b6b70; margin-top:9px;
    font-family:ui-monospace,SFMono-Regular,Menlo,monospace; letter-spacing:.02em; }
</style></head>
<body>
  <h1>Chart rebuttal cards</h1>
  <p class="sub">${cards.length} cards at 1600\u00d7900. Regenerated by <code>pnpm render:charts</code>.</p>
  <div class="grid">
${rows}
  </div>
</body></html>
`)
console.log(`\nwrote og-cards/gallery.html (${cards.length} cards)`)
